function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=1/params(1)-1;
    ys_(2)=2.05098409;
    ys_(4)=25.40685351;
    ys_(3)=1;
    ys_(6)=0;
    ys_(5)=3.20466265;
    ys_(7)=0.63517134;
    ys_(8)=2.56949131;
    ys_(9)=10.94366342;
    ys_(15)=0;
    ys_(13)=0;
    ys_(17)=0;
    Cbt=0;
    Cmt=0;
    Ctt=0;
    ys_(11)=0;
    ys_(10)=0;
    ys_(12)=0;
    ys_(14)=0;
    ys_(16)=0;
    ys_(18)=0;
    % Auxiliary equations
end
